import Head from "next/head";
import React from "react";
import Image from "next/image";
import Interest from "./interest";
import { useRouter } from "next/router";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Script from "next/script";
import "bootstrap/dist/css/bootstrap.css";
import Product from "@/models/Product";
import mongoose from "mongoose";

const inter = Inter({ subsets: ["latin"] });

const Home = ({ products }) => {
  console.log("olo", products);
  const router = useRouter();
  const {
    query: { study, gender, army, agedate, agemonth, ageyear },
  } = router;
  const props = { study, gender, army, agedate, agemonth, ageyear };
  console.log("hap", props.army);
  console.log("llmm age:-", props.ageyear);
  console.log("llmm month:-", props.agemonth);
  return (
    <>
      <div>
        <Head>
          <title>Join Forces Serve Nation</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/army_logo.png" />
        </Head>
        <Link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossOrigin="anonymous"
        />
        <div
          id="carouselExampleCaptions"
          className="carousel slide md:-mt-20 -mt-1"
        >
          <div className="carousel-indicators">
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="0"
              className="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="1"
              aria-label="Slide 2"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="2"
              aria-label="Slide 3"
            ></button>
          </div>
          <div className="carousel-inner">
            <div className="carousel-item active">
              <Image
                width={1000}
                height={1000}
                src="https://media.istockphoto.com/id/1454562653/photo/26-january-background-republic-day-india-and-republic-day-background-screen.jpg?s=612x612&w=0&k=20&c=LuIluzv105ci1Ut0X4XVk7zQ1yJ41dNOIcm4Yhc5O_0="
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5">
                <h5 className="text-2xl mb-2">First slide label</h5>
                <p className="text-2xl">
                  Some representative placeholder content for the first slide.
                </p>
              </div>
            </div>
            <div className="carousel-item">
              <Image
                width={1000}
                height={1000}
                src="https://static.theprint.in/wp-content/uploads/2020/02/Indian-Army-4.jpg"
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5">
                <h5 className="text-2xl mb-2">First slide label</h5>
                <p className="text-2xl">
                  Some representative placeholder content for the first slide.
                </p>
              </div>
            </div>
            <div className="carousel-item">
              <Image
                width={1000}
                height={1000}
                src="https://media.istockphoto.com/id/1454563213/photo/republic-day-celebration-gantantra-diwas-and-republic-day-art.jpg?s=612x612&w=0&k=20&c=dwklSQBICUQW_zNZO6LilAfb79Pj4X3X1lZnIY0_E7M="
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5">
                <h5 className="text-2xl mb-2">First slide label</h5>
                <p className="text-2xl">
                  Some representative placeholder content for the first slide.
                </p>
              </div>
            </div>
          </div>
          <button
            className="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev"
          >
            <span
              className="carousel-control-prev-icon"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Previous</span>
          </button>
          <button
            className="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next"
          >
            <span
              className="carousel-control-next-icon"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Next</span>
          </button>
        </div>
        <section className="container dark:bg-slate-800 h-96">
          <div className="flex flex-col text-center w-full">
            <h1 className="sm:text-3xl py-2 text-2xl font-medium title-font my-4 text-gray-900 dark:text-gray-100 dark:bg-slate-700">
              Get the data of all defence forces on a single platform
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-lg dark:text-gray-300 -mt-4">
              Check your eligibility criteria in the advanced search system ...
            </p>
            <Link
              href={"/tshirts"}
              className="flex mx-auto mt-4 text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg"
            >
              Check Eligilbiliy
            </Link>
          </div>
          <div className="absolute right-10 bg-slate-300 w-1/4 p-4 rounded-md -mt-36">
            <h2 className="flex justify-center items-center text-red-500 mb-3 text-lg font-bold">
              Current Updates
            </h2>
            <p className="my-3">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo
              nemo accusamus temporibus corporis corrupti impedit, minima
              exercitationem consequatur ratione eaque deleniti aspernatur enim
              dolorum, praesentium quae mollitia autem doloremque veritatis?
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Similique maxime, itaque praesentium consectetur facilis ratione
              iusto est iure quisquam ea impedit molestiae tenetur reprehenderit
              nobis reiciendis illo mollitia nemo debitis.
            </p>
          </div>
        </section>
        {/* <div className="flex flex-wrap justify-center items-center my-5">
          {Object.keys(products).map((item) => {
            return 
            <div
                  key={products[item]._id}
                  onClick={() => {
                    const elems = document.querySelectorAll(
                      `.${products[item].slug}`
                    );
                    [].forEach.call(elems, function (el) {
                      el.classList.toggle("hidden");
                    });
                    blur();
                  }}
                  className="xl:w-1/3 lg:w-1/3 md:w-1/2 w-full px-8 my-2 mx-2 py-6 border-l-2 border-gray-200 border-opacity-60 bg-slate-300 rounded-xl shadow-sm hover:bg-stone-300 hover:shadow-lg hover:rounded-md cursor-pointer"
                >
                  <h2 className="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                    {products[item].title}
                  </h2>
                  <div className="flex mb-2">
                    <div className="leading-relaxed text-base font-semibold">
                      <b> Age - </b>
                      {products[item].title_age}
                    </div>
                  </div>
                  <div className="flex mb-2">
                    <div className="leading-relaxed text-base">
                      <b>Qualification - </b>
                      {products[item].title_qualification}
                    </div>
                  </div>
                  <div className="flex mb-2">
                    <div className="leading-relaxed text-base">
                      <b>Eligibility - </b>
                      {products[item].title_eligibility}
                    </div>
                  </div>
                  <div className="flex mb-2">
                    <div className="leading-relaxed text-base">
                      <b>Post - </b>
                      {products[item].title_post}
                    </div>
                  </div>
               </div>
              )
            )
          })}
        </div> */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossOrigin="anonymous"
        />
      </div>
    </>
  );
};
export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URL);
  }
  let products = await Product.find();

  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    }, // will be passed to the page component as props
  };
}
export default Home;
