import Head from "next/head";
import React from "react";
import Image from "next/image";
import Interest from "./interest";
import { useRouter } from "next/router";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Script from "next/script";
import "bootstrap/dist/css/bootstrap.css";
import Product from "@/models/Product";
import mongoose from "mongoose";

const inter = Inter({ subsets: ["latin"] });

const Home = ({ products }) => {
  console.log("olo", products);
  return (
    <>
      <div>
        <Head>
          <title>Serve Nation by Joining the Forces</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/army_logo.png" />
        </Head>
        <Link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossOrigin="anonymous"
        />
        <div
          id="carouselExampleCaptions"
          className="carousel slide md:-mt-20 -mt-1"
        >
          <div className="carousel-indicators">
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="0"
              className="active"
              aria-current="true"
              aria-label="Slide 1"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="1"
              aria-label="Slide 2"
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="2"
              aria-label="Slide 3"
            ></button>
          </div>
          <div className="carousel-inner">
            <div className="carousel-item active">
              <Image
                width={1000}
                height={1000}
                src="https://media.istockphoto.com/id/1454562653/photo/26-january-background-republic-day-india-and-republic-day-background-screen.jpg?s=612x612&w=0&k=20&c=LuIluzv105ci1Ut0X4XVk7zQ1yJ41dNOIcm4Yhc5O_0="
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5 absolute top-48">
                <h5 className="text-3xl font-bold text-zinc-300">
                  SERVENATION - "Serve the Nation, Strengthen the Future"
                </h5>
                <p className="text-2xl mt-5">
                  "The willingness to serve for the nation is a testament to
                  one's love and devotion for their country."
                </p>
                <p className="text-2xl my-3 text-gray-100">
                  "Joining the armed forces is not just a career choice, it's a
                  commitment to defend our nation and protect our freedoms."
                </p>
                <Link href={"/tshirts"} className="text-2xl text-gray-100">
                  Join Us ...
                </Link>
              </div>
            </div>
            <div className="carousel-item">
              <Image
                width={1000}
                height={1000}
                src="https://static.theprint.in/wp-content/uploads/2020/02/Indian-Army-4.jpg"
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5 absolute top-48">
                <h5 className="text-3xl font-bold text-gray-800">
                  SERVENATION - "Serve the Nation, Strengthen the Future"
                </h5>
                <p className="text-2xl mt-5 text-gray-500">
                  "The willingness to serve for the nation is a testament to
                  one's love and devotion for their country."
                </p>
                <p className="text-2xl my-3 text-gray-600">
                  "Joining the armed forces is not just a career choice, it's a
                  commitment to defend our nation and protect our freedoms."
                </p>
                <Link href={"/tshirts"} className="text-2xl text-gray-700">
                  Join Us ...
                </Link>
              </div>
            </div>
            <div className="carousel-item">
              <Image
                width={1000}
                height={1000}
                src="/1358662.jpg"
                className="d-block w-full md:h-screen h-72"
                alt="..."
              />
              <div className="carousel-caption d-none d-md-block my-5 absolute top-48">
                <h5 className="text-3xl font-bold text-gray-900">
                  SERVENATION - "Serve the Nation, Strengthen the Future"
                </h5>
                <p className="text-2xl mt-5 text-gray-900">
                  "The willingness to serve for the nation is a testament to
                  one's love and devotion for their country."
                </p>
                <p className="text-2xl my-3 text-gray-900">
                  "Joining the armed forces is not just a career choice, it's a
                  commitment to defend our nation and protect our freedoms."
                </p>
                <Link href={"/tshirts"} className="text-2xl text-gray-300">
                  Join Us ...
                </Link>
              </div>
            </div>
          </div>
          <button
            className="carousel-control-prev"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev"
          >
            <span
              className="carousel-control-prev-icon"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Previous</span>
          </button>
          <button
            className="carousel-control-next"
            type="button"
            data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next"
          >
            <span
              className="carousel-control-next-icon"
              aria-hidden="true"
            ></span>
            <span className="visually-hidden">Next</span>
          </button>
        </div>
        <section className="container dark:bg-slate-800">
          <div className="flex flex-col text-center w-full">
            <h1 className="sm:text-3xl py-2 text-2xl font-medium title-font my-4 text-gray-900 dark:text-gray-100">
              Get the data of all defence forces on a single platform
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-lg dark:text-gray-300 -mt-4">
              Check your eligibility criteria in the advanced search system ...
            </p>
            <Link
              href={"/tshirts"}
              className="flex font-bold mx-auto my-4 text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg"
            >
              Check Eligilbiliy
            </Link>
          </div>
          {/* <div className="bg-gray-400 border-2 border-black rounded-lg mt-5 p-3">
            <h2 className="flex justify-center items-center text-red-500 mb-3 text-lg font-bold">
              Current Updates
            </h2>
            <p className="my-3">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo
              nemo accusamus temporibus corporis corrupti impedit, minima
              exercitationem consequatur ratione eaque deleniti aspernatur enim
              dolorum, praesentium quae mollitia autem doloremque veritatis?
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Similique maxime, itaque praesentium consectetur facilis ratione
              iusto est iure quisquam ea impedit molestiae tenetur reprehenderit
              nobis reiciendis illo mollitia nemo debitis.
            </p>
          </div> */}
        </section>
        <section className="md:flex md:flex-wrap justify-center items-center py-5 md:space-x-5 space-y-3 md:space-y-0 dark:bg-slate-500">
          <div className="card md:w-1/4 w-11/12 ml-4 border-2 border-gray-600 shadow-lg hover:bg-gray-100 hover:shadow-2xl">
            <Image
              width={300}
              height={300}
              src="https://as2.ftcdn.net/v2/jpg/03/14/63/11/1000_F_314631142_LHRv0woK2XJ82pRu6rqgcuWKhg8HLzpW.jpg"
              className="card-img-top"
              alt="..."
            />
            <div className="card-body">
              <h5 className="card-title">Indian Army</h5>
              <p className="card-text">
                The Indian Army is the land-based branch and the largest
                component of the Indian Armed Forces. The President of India is
                the Supreme Commander of the Indian Army, and its professional
                head is the Chief of Army Staff, who is a four-star general.
              </p>
              <Link href="/" className="btn btn-primary mt-3">
                Learn More
              </Link>
            </div>
          </div>
          <div className="card md:w-1/4 w-11/12 ml-4 border-2 border-gray-600 shadow-xl hover:bg-gray-100 hover:shadow-2xl">
            <Image
              width={300}
              height={300}
              src="https://img.etimg.com/thumb/msid-73281276,width-1200,height-900,imgsize-778178,overlay-etdefence/photo.jpg"
              className="card-img-top"
              alt="..."
            />
            <div className="card-body">
              <h5 className="card-title">Indian Navy</h5>
              <p className="card-text">
                The Indian Navy is the maritime branch of the Indian Armed
                Forces. The President of India is the Supreme Commander of the
                Indian Navy. The Chief of Naval Staff, a four-star admiral,
                commands the navy.The maritime history of India dates back 6,000
                years to the Indus Valley civilisation.
              </p>
              <Link href="/" className="btn btn-primary mt-3">
                Learn More
              </Link>
            </div>
          </div>
          <div className="card md:w-1/4 w-11/12 ml-4 border-2 border-gray-600 shadow-lg hover:bg-gray-100 hover:shadow-2xl">
            <Image
              width={500}
              height={500}
              src="https://images.news18.com/ibnlive/uploads/2021/02/1612436324_pti02_04_2021_000111b-1.jpg?impolicy=website&width=0&height=0"
              className="card-img-top"
              alt="..."
            />
            <div className="card-body">
              <h5 className="card-title">Indian Air Force</h5>
              <p className="card-text">
                The Indian Air Force is the air arm of the Indian Armed Forces.
                Its complement of personnel and aircraft assets ranks as the
                third most powerful air force in the world. Its primary mission
                is to secure Indian airspace and to conduct aerial warfare
                during armed conflicts.
              </p>
              <Link href="/" className="btn btn-primary mt-3">
                Learn More
              </Link>
            </div>
          </div>
        </section>

        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossOrigin="anonymous"
        />
      </div>
    </>
  );
};
export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URL);
  }
  let products = await Product.find();

  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    }, // will be passed to the page component as props
  };
}
export default Home;
